/**
 * Download the web fonts and rewrite them as local @font-face rules.
 *
 * The Production PC is airgapped: an @import from fonts.googleapis.com there does
 * not fail loudly, it just never resolves — the browser silently falls back to a
 * system font and the whole Cyber-Ops type system quietly collapses. Fonts must
 * ship inside the bundle.
 *
 * Run on the Dev PC (needs internet) whenever the font set changes:
 *   node scripts/vendor-fonts.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const FAMILIES =
  'family=Space+Grotesk:wght@500;700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600';
const CSS_URL = `https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`;

// Latin covers the UI; Vietnamese covers ticket content. Cyrillic/Greek are dead
// weight in an offline bundle.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'vietnamese']);

// A modern UA is what makes Google serve woff2 instead of legacy formats.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const OUT_DIR = path.resolve('public/fonts');
const CSS_OUT = path.resolve('src/fonts.css');

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => r.text());

mkdirSync(OUT_DIR, { recursive: true });

// Google emits `/* subset */\n@font-face { ... }` blocks in sequence.
const blocks = css.split('/*').slice(1);
const kept = [];

for (const raw of blocks) {
  const subset = raw.slice(0, raw.indexOf('*/')).trim();
  if (!KEEP_SUBSETS.has(subset)) continue;

  const face = raw.slice(raw.indexOf('@font-face'));
  const url = face.match(/url\((https:[^)]+)\)/)?.[1];
  const family = face.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = face.match(/font-weight:\s*(\d+)/)?.[1];
  if (!url || !family || !weight) continue;

  const file = `${family.replace(/\s+/g, '')}-${weight}-${subset}.woff2`;
  const bytes = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()));
  writeFileSync(path.join(OUT_DIR, file), bytes);

  kept.push(
    face
      .replace(/url\(https:[^)]+\)/, `url('/fonts/${file}')`)
      .replace(/\}[\s\S]*$/, '}')
      .trim(),
  );
  console.log(`${file}  ${(bytes.length / 1024).toFixed(1)} KB`);
}

const header = `/* GENERATED by scripts/vendor-fonts.mjs — do not edit by hand.
   Self-hosted so the app renders correctly on the airgapped Production PC,
   where fonts.googleapis.com is unreachable. */\n\n`;

writeFileSync(CSS_OUT, header + kept.join('\n\n') + '\n');
console.log(`\n${kept.length} @font-face -> src/fonts.css`);
